### ISSUE TITLE
Strange echoes?

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#10]
Haven't got past circa `121:48` yet, but noticed there's duplication in the soundtrack there.

Is that in the original material, some kind of echoing effect, or an edit glitch?

Cheers!

**Comment by bfeist** [comment]
That's the result of the astronauts' microphones picking up the speakers in their helmets when they were turned up a little too loud. You're hearing the delay due to the distance of the moon.

**Comment by mjtorn** [comment]
Yeah, guessed as much, but thanks for clearing it up :)
