### ISSUE TITLE
VHF OCR mistake

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#11]
`156:10:51` reads "Command Module VHP off" though Mission Control clearly says VHF :)

**Comment by mjtorn** [comment]
`156:19:44` I'm sure Evans says "cut open", though the transcript says "cup", which wouldn't even make that much sense...

**Comment by mjtorn** [comment]
And `161:21:32` seems totally broken; even if I hit the transcript, there's no audio.

**Comment by bfeist** [comment]
Thanks again! Fixed
