### ISSUE TITLE
.small ones

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#12]
Hi!

Noticed `166:55:42` transcribed as ".small ones", with an extra period there. You have this in the develop branch under `Corrections from others` so did you get this from someone? The Excel files don't seem to contain it.

**Comment by mjtorn** [comment]
Another one's at `180:19:40` - "coming up on tine to start" where it should say time.

**Comment by bfeist** [comment]
Thanks for these. Fixed. The master branch is the up-to-date branch now. "corrections from others" is just my commit comment and covers the entire transcript.
