### ISSUE TITLE
Silent video

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#13]
The video is silent roughly from `184:17:30` to `186:01:44`. I did not listen through all the silence, so I don't know if it's continuously like that or not.

The transcript also seems to glitch a bit at `184:15:11`.

Fortunately not a whole lot seems to be happening there and maybe skipping to launch is a good thing because of all the vacation/holiday-long breaks I've had to have in watching this ;)

**Comment by mjtorn** [comment]
`189:52:02` "comer" should be "corner", OCR moment there

**Comment by mjtorn** [comment]
And `189:52:35` should _maybe_ read "plain-faced barrel", but not 100% sure. Sounds like that's what he said.

And slight glitchage at `189:56:02`-`189:56:11`

**Comment by bfeist** [comment]
Thanks for these. The silent video is part of the audio that NASA has not yet digitized. There are also hours of missing audio on the day prior to reentry. I'm waiting to get my hands on it. In those sections, the transcripts contain multiple lines with the same timecode--these are approximations based on the original transcripts.

**Comment by mjtorn** [comment]
Yeah ok, not there yet :)

BTW `190:14:03` reads CMS when it should read CSM. This is how much I got to listen to this over the weekend.
