### ISSUE TITLE
Some OCR mistakes more

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#14]
Hi!

`214:25:25` has "valve" for _value_ and "miiligal" for _milligal_

**Comment by mjtorn** [comment]
`214:34:21` I'm pretty sure it's spelled "mystery"

**Comment by mjtorn** [comment]
`215:28:07` probably should say `pool-bottomed`

**Comment by bfeist** [comment]
Thanks so much for these. I really appreciate it!

**Comment by mjtorn** [comment]
You're naturally welcome, @bfeist :)

I forgot to submit this, found it open in my browser: `215:33:47` "ejeeta blanket" -> "ejecta blanket" (this sounds like something that could occur elsewhere as well)

**Comment by bfeist** [comment]
thanks, got it

**Comment by bfeist** [comment]
You know, if you like, I can send over the transcript data file. You can correct as you go (if you're still going) and I can review and merge your changes in bulk. drop me an email if you're interested (bf at benfeist.com)

**Comment by mjtorn** [comment]
`220:01:10` `Apollo 17 The following` is missing a `.`

**Comment by mjtorn** [comment]
@bfeist thanks for the offer but I think I have a git clone of this at home... and it's so much easier for me to type these up here, so much that maintaining a branch or file copy would be an actual bother... Not least because I take notes on where I left off in case I get to pick up again on another computer...

So because it's hard enough to listen to this, sometimes impossible during the weekends, and not always that I can pay attention to the transcript, I'm afraid direct editing would be too cumbersome, sorry :( I could theoretically use the web interface to update a fork of mine, but that's not as convenient as it sounds and it might lower the bar for double-checking. Currently I have a tab for these next to the actual site, which is practically zero effort to me and I'd like to think these are double checked.

I'm paused at `218:40`, but I think it'd help if I collect these somewhere and make a bigger report at once. Maybe have a private gist tab instead and submit the findings every once in a while, if/when they arise.

Then we can also hope there are no more OCR mistakes ;)

**Comment by bfeist** [comment]
Not a problem at all. Keep em coming!
