### ISSUE TITLE
Some more possible corrections

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#15]
I'll try to heave these in in larger batches, even at the risk that someone else caught these. Been kinda busy, might have missed a bunch, the usual disclaimers ;)

`229:15:11` the news reading; `tut the report` -> "but the report"
`president Kixon` -> "president Nixon"
`assignment nay be` -> "assignment may be"
`John Scaii` -> (sounds like) "John Scali" and also `A3C` -> `ABC`
`. a format` -> ". A formal"
`Major Joe Dennis` -> (I'm sure he said) "Mayor Joe Dennis"
`Mrs Kart is currently` -> "Mrs Hart is currently"
(Also if the plane type is spelled "single-engine" in English, there's a `singleengine`)

`229:28:20` `reao` -> "read" but audio's missing for that.
`229:29:05` `catsup` -> "ketchup", right? and `gravy5 chocolate bar` seems like a typo
`229:29:05` `catsup` -> "ketchup", right? or are both correct spellings?

`229:52:01` `then` and `then.` -> "them"
`229:55:53` `trie` -> "the" (there could be more of these, seems like it could be a common one)

`232:15:53` `awhile` -> I think it's "a while" in English but not sure

`233:21:30` `interestea` -> "interested"

`233:29:29` `you-do` -> That dash probably shouldn't be there

`233:32:04` `alor.g` -> "along", `indisinguishable .` -> "indisinguishable." (without an extra space)

`233:34:07` `lateral or echelon structure` I could swear he says "on" but I'm not a geologist nor is this my first language ;)

`233:46:45` `47:15s` the "s" is probably a mistake

`234:01:09` Looks like the font reads `R-l` but he says "R-1"

`235:39:01` `Gordy. is` -> "Gordy. Is"

`236:22:29` `it's path back` -> "its path back"

`236:57:14`, `236:57:59` call sign/name/whatever missing

`236:59:21` `lunan` -> "lunar"

`237:00:29` Sure he says "DELTA-VGx" or something, and "DELTA-Vc"

`237:02:07` `far aide` -> "far side"

`237:04:47` `ana apparent` -> "and apparent"

`237:10:08` `point` doesn't he say "pointing"?

`237:15:45` sounds more like Evans than Schmitt

**Comment by bfeist** [comment]
Thanks so much! You're a life saver. All changes made except for "catsup"--that's an alternative spelling more prevalent back in the time of the mission.

**Comment by mjtorn** [comment]
Just happy to be of help :)
