### ISSUE TITLE
Updates again

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#16]
Been really slow progress lately, seems that the real-time stream will soon be in sync with me :D Maybe some of these haven't been reported by anyone else:
`237:48:47` `Tranquillity` -> "Tranquility". This is something there could be more of. Wikipedia confirms the spelling is "Tranquillitatis" for Latin, "Tranquility" for English

`237:22:04` `snow up` -> "show up"

`237:25:06` `Symthii` -> "Smythii"

`237:28:49` `taKe` -> "take"

`238:01:41` `Negative, But` that should probably be `but` (he goes too fast for the comma to be a period IMO)

`238:02:15` `Communications; Officer` -> "Communications Officer"

`238:08:55` `annulus - =the` -> "annulus - the"

`239:15:02` `it's sleep` -> "its sleep"

`243:07:41` `higjh gain` -> "high gain"

`243:08:47` `SC` were you correcting these or do I remember wrong?

`249:37:01` `nautical miles: from Earth.` -> "nautical miles from Earth"

`251:17:45` `It's net really` -> "It's not really"

`251:58:11` `ve're working` -> "we're working"

`252:30:01` `CMPs` ->  "CMP's" (right?)

`252:37:29` `Borth Vietnam` ->  "North Vietnam", `thi.-President` I'm quite sure he said "the President", `supervisee` -> "supervised"

At `254:54:39` the transcript didn't move forwards, similar at `255:02` - there was more of this around Evans' EVA

`254:55:40` Pretty sure it should read `Once you've`

`255:32:48` `.Okay` -> "Okay"

`255:43:13` `in w suit` -> "in the suit" (unless this is Polish or something ;)

`256:28:36` `loud and clear;` -> "loud and clear."

`257:00:16` `Okay. is` -> "Okay. Is"

`258:05:21` `. is there` -> ". Is there"

**Comment by mjtorn** [comment]
`258:46:28` `depres-surization` -> "depressurization"

`258:58:53` and many others before that failed to scroll the transcript

`259:29:51` `If you. have` -> "If you have"

`259:30:13` I could swear he says "We're _in_ OMNI Delta", which is not so in the transcript

`259:56:53` `a dam good spacecraft` -> "a damn good spacecraft"

**Comment by bfeist** [comment]
Thanks for these! I'm in Vancouver on business and will address these next
week. Thanks again for the help. You're the only person submitting these
fixes and I really appreciate your help in making the record better.

Ben

**Comment by mjtorn** [comment]
I'm just happy to contribute ;)

BTW `262:15:37` says `MODE's` but just above it the suffix s was a capital S (like the word), but I can't actually remember which one there's more of ;)

**Comment by bfeist** [comment]
I think the items you listed as not scrolling are due to javascript slowing down on your machine. It currently polls for a new transcript item every 0.5 seconds. If for some reason your computer is behind on is JS tasks, this polling can be delayed past 1 second resulting in it missing the scroll item. Just a guess. I couldn't find any bad data in the utterance data to account for this. A good way to test is to try to scroll through those same items after a reload.

**Comment by mjtorn** [comment]
Yeah, I reload occasionally, but the issue with that is that (as much as I love the "slider" UI) getting to where I left off can be a bit of a hassle. It'd actually make for a nice feature request to be able to input the GET somehow...
