### ISSUE TITLE
New this week

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#19]
`281:43:07` `RET 9OK` he says `RET 90K`

`284:23:10` `into space If` I think that could be "into space, if" or maybe "into space if"

`284:23:43` almost as if `isn't` is added in the transcript, and the rest would read `truly indeed has really been a beginning`

`284:30:06` doesn't he say "as submitted"? `as` missing from the transcript

`284:30:28` Looks like the "I uhh" is cleaned up, fine, but `vex-y` is not right. Looks like transcribed "very" but he might say "fairly", not sure I picked that up right

`284:31:11` Evans says "all of the vehicles", transcript says `all the vehicles`

`287:02:26` `FAN 2` -> "H_2 FAN 2"

Been the busiest week ever, don't think I covered a lot of hours at all :D Let's see how long it takes for me to watch through the last 20 or so hours I have remaining, probably weeks ;)

**Comment by bfeist** [comment]
Thanks again. You have a real gift for looking at the details. Let's do Apollo 16 together :P

**Comment by mjtorn** [comment]
Hehe, it's a blessing and a curse, like reading a paper novel and not being able to "Submit content error" like on a Kindle when there are typos ;)

Is Apollo 16 actually available to the same extent as Apollo 17?

**Comment by bfeist** [comment]
I haven't taken a close look, but I'm sure Apollo 16's data is in much better shape than 17 was.

**Comment by mjtorn** [comment]
If you make a similar site of that material and I hear about it, sure I'd watch it and hopefully get to send in mistakes I spot ;) Actual collaboration would be interesting but I couldn't commit to such a huge undertaking off the bat and it might be better for everyone that the launch wouldn't depend on me being busy :(
