### ISSUE TITLE
Audio loss and duplicate timestamps

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#20]
`287:32:08` `it's ultraviolet spectrometer` -> "its"

`287:53:02` `simply -simply` -> "simply - simply", formatting like all the others

`288:05:51` `VERB 49,` -> "VERB 49."

The background static dropped off every once in a while, probably due to the source
material and I haven't really reported these, but one occurred after `289:35:31`,
and it didn't recover at `289:56:02` probably because of the overlapping utterances.

The last `289:56:02` `news ,` -> "news, "

Similarly broken at `290:02:30`, no audio, but Mission Control's broken with `you If`,
though I can't say if there should be a period or comma there.

I think I'll give this some pause, it looks like a ton of trouble ahead with duplicate GET codes :/

(I did refresh real hard to make sure this isn't a known fixed issue, but let me know if there's
an issue on my side)

**Comment by bfeist** [comment]
Thanks for these. I've made the first 3 corrections. Any segment with duplicate timecodes is missing source audio. I'm waiting for NASA to digitize these last segments. Until then there's nothing to correct the transcript against. You can safely skip over these segments to a point where the timecodes don't duplicate (making duplicate times was part of a previous step I took in reconstructing the transcript. Almost the entire mission was like this until I corrected via the audio).

**Comment by mjtorn** [comment]
I'll be away for a while so it'll take even longer to actually get to splashdown, unless I get a lucky break somewhere ;)

So I'll leave these here:

`300:20:28` `GETT` -> "GET", Schmitt got it right in the readback, but the transcript didn't

`300:32:11` sounds an awful lot like Evans, not Mission Control, though there's something going on in the audio

**Comment by bfeist** [comment]
Thanks!
