### ISSUE TITLE
Last ones

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#21]
Been very _very_ hectic lately for me but I finally got through to the end, and boy was it great :D

Hope I didn't miss anything, I was taking very quick notes for a long time and then had the fortune of watching the recovery almost in one go, but here's something for you to check:

`301:10:01` `BUSS/dumping` slash character correct?

`301:18:15` the comma

`301:38:23` pago pago -> pango pango

`303:08:25` misplaced, on purpose? after the `203:43:06` bunch

even without audio `303:07:25` `fi ne` -> "fine"

`303:36:40` and others, a stereo mix would be nicer than overlap/cutoff but these were there before and I guess not doable?

`303:47:32` wasn't there another change like "TAPE RECORDER's" with a lowercase s, because only the certain nouns are in all caps?

`303:45:15` "6-1/2 g's" I think most of the "six and a half" style utterances have been without dashes

`304:01:54` `I see it! it's` -> "I see it! It's"

`304:07:19` `amont` -> "among"

`304:12:23` `it's` -> "It's"

`304:15:01` `R-1` and `R-2` are correct in this instance? The call signs do get a bit random later

`304:19:01` `Tyconderoga` -> "Ticonderoga"

`304:24:21` `is that on time?` -> "Is that on time?"

`304:33:07` `Okay,(garble)` would be clearer with a space after the comma

`304:33:10` `(garble)` -> "(Garble)" there's some inconsistencies with this later on you may want to check out, maybe change `304:32:45` to lowercase for less effort

`304:33:41` `Chopper` -> "chopper" (not a name, right?)

`304:35:25` and `304:35:39` `3-1/2 miles` -> "3 1/2 miles" (unless most are with dashes but then the others may want attention)

`304:36:34` Does SPKR whoever actually end with "keep cranking the valve"? Does that make sense?

`304:38:59` Not sure what's going on here, it's as if there's `(garble)` missing there

`304:46:12` `collar's` -> "collar is"

`304:49:49` `GARBLE` -> `(garble)`

`304:56:45` or so, the Public Affairs transcript is missing

`305:34:33` is mispaced between `304:56:38` and `304:57:21`

`304:57:21` `motor whale` -> "motor whale boat"

`305:15:22` `Astronauts` -> "astronauts"

`305:22:11` `was` -> "is" as he says

`305:24:56` `placque` -> "plaque", right? Not sure about the spelling, but this was inconsistent earlier

`305:32:55` Another inconsistent `6-1/2 years ago`

`205:35:24` After "stiff-upper-liping it" he says "with talk of Skylab" but that's not in the transcript

Thanks a million for creating this show!

Wonder if it caught the eye of Cernan and Schmitt and whoever may still be alive who contributed to the mission :)

**Comment by bfeist** [comment]
Thanks for all of this! And thank you so much for taking the time to contribute to the project. You're the only person I know of who has watched the whole thing. Having a second set of eyes on it to catch inconsistencies and errors has been hugely helpful.

I heard through the grapevine that Schmitt has seen the site. He thought it was "great". I also heard that Gene Kranz had seen it and thought it was nice to see "the mission live once again". Super exciting to hear that people involved in the real thing appreciate my work. Humbling to say the least.

**Comment by mjtorn** [comment]
What can I say, I grew up on The Right Stuff and From the Earth to the Moon, as well as the usual scifi, so how could I pass up on something like this :)

I can only imagine what it feels like for you to have stars like Schmitt and Kranz appreciate your work, but it's been an honor contributing and I'm really happy for you and everyone else that this site exists.
