### ISSUE TITLE
Potential breakage

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#4]
Noticed the lines starting at `43:30:40` don't seem to be in sync; it's followed by `43:36:28` and then `43:31:47`.

Also, not sure if this is too nitpicky, but "ROOSA" looks odd in all caps there.

**Comment by mjtorn** [comment]
`59:05` or so should read "16 passengers", now it's without the space :)

**Comment by bfeist** [comment]
Thanks for the detail. ROOSA is the capcom name. Eventually i'll be replacing "mission control" with capcom names, so I'll leave that there for now. The other timings were off by about a second. I made some changes to make them closer, but the way youtube works is probably only good within a second anyway. There will be many more utterances that are off by this much. I appreciate the help.
