### ISSUE TITLE
Timeline links

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#5]
Unfortunately I can view this only in the background at work and sometimes I have to skip around to stay even remotely in sync (as I can't sync my life to their rest period) but I noticed Evans and his scissors `069:33:00` popped up at some point.

Now I'm getting to the ALFMED part, noticing that if I hit the `068:03:55` image, it skips forward to Evans and his scissors again.

Maybe it's about their clock time update, or maybe it's something else, but it would be nice seeing the pictures :)

**Comment by mjtorn** [comment]
Unrelated, I noticed at least one Plight (sic) plan and something with "rnp" instead of "mp" like before. I was thinking of making a pull request instead of issues but, sorry, unfortunately the files are too huge. But maybe if you grep around for "plight" and "rnp" you'll find a lot of OCR goodness.

**Comment by mjtorn** [comment]
`068:07:51` seems to kick off some 10-second delay. Evans goes on air at `068:11:14`, which is 10 seconds sooner than the transcripted time codes, as well as the transcript window skipping over some communication that's not heard. Might just be a Youtube moment or something, but just letting you know in case it's something real.

**Comment by mjtorn** [comment]
`71:33:04` he says "some friends" but the transcript says "same friends"

**Comment by bfeist** [comment]
Very much appreciate your help. That 068:07:51 sync error was a big one. All timed correctly now.

**Comment by mjtorn** [comment]
My pleasure, just hope I can keep up :)

Youtube - or my home desktop - isn't making it easy; real hard time getting video of the current timestamp or where I'd like to skip to.

Doubt this is an issue in the code, as the `seekToTime()` through `trimUtterances()` calls show up quickly in Firebug.

Anyway, you're more than welcome :)

**Comment by bfeist** [comment]
If youtube buffers there's not much that can be done except upgrade your internet connection :) It's incredible that we live in a time where this can all work together to begin with--all running in your browser

**Comment by mjtorn** [comment]
Absolutely, and listening to degrees loaded into Noun 22 makes me think that it's ok to be behind in the stream and skip ahead later. Those guys went to the moon with that type of computer (and the imperial system of measurement!) so we kids today shouldn't be complaining about free and easy things not working properly all the time :)
