### ISSUE TITLE
Duplicate timestamp

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#6]
Noticed this at `086:27:42`, there are two lines with the same time stamp. In the transcript Mission Control asks to toggle the UV and then asks to copy a voice check, but the second one isn't heard until `086:32:32` or so.

Wish I had the hard drive capacity currently to do a git clone, maybe I can do it later on other hardware if I have time, but it should be almost a Python one-liner to check for duplicates in the transcript data. Is this possible for you to do?

Thanks!

**Comment by mjtorn** [comment]
And `086:36:50` says `sP00n` :D maybe a word-bounded check for P00, if there are more of these?

**Comment by mjtorn** [comment]
`90:24:00` seems to come a bit too soon and my gut tells me the Lunar orbit sequence may have timing issues in general, but I haven't had time to work right now to really focus on it, but as a heads-up... Unless those are exactly the Youtube timings where their precision doesn't cut it or something :)

**Comment by mjtorn** [comment]
`93:45:51` "controvery" must be a typo, sure he said "controversy"

**Comment by bfeist** [comment]
Thanks again! the sP00n was search and replace gone awry. 90:24:00 was bang on in the source video, so you might just be behind a bit somehow on youtube. I've never experienced this but it's possible if you're on a slower connection and getting a different quality level of video from youtube I suppose.

Again, much appreciate you taking the time to point these errors out.
