### ISSUE TITLE
Audio discrepancy during the telescope video

### ISSUE THREAD

**Issue by mjtorn** [bfeist/Apollo17.org#7]
Found one more, fortunately, though this one's pretty obvious so you may have got it elsewhere.

Watching at around `106:09` there's talk that's transcribed at `106:54:49`.

How can that be, as it's repeated at `106:54`? Is there an issue with the soundtrack on the Youtube video?

**Comment by mjtorn** [comment]
Also going from `111:00:47` it seems Mission Control might be a bit off the transcript, but this is amazing stuff either way :)

**Comment by bfeist** [comment]
Thanks for these. The 106:09 issue was an error where I left a long bit of recording in the wrong place. Thanks for the catch! I now have to rerender 16 hours of video :)
